### PR TITLE
Add sourcemaps, add better errors, cleanup tests, and update esperanto

### PR DESCRIPTION
**Pull request by thejameskyle**
Lot of changes in here:
- Upgraded esperanto (and other deps)
- Cleaned up options (don't depend on typeMap)
- Add source map support
- Emit errors from esperanto instead of throwing them
- Cleanup tests (no need to retest esperanto's output, it is already testing that, and it gets in the way of upgrading)

### CODE REVIEW

**Comment by Attamusc** [comment]
Awesome! Changes make sense; will merge. Thanks for the PR :)

**Comment by thejameskyle** [comment]
@Attamusc would you mind making another release?

**Comment by Attamusc** [comment]
Sure thing. Was planning on doing that as soon as I'm in front on my computer. Should be up soon

**Comment by Attamusc** [comment]
@thejameskyle Released as `0.2.0`

**Pull request merged**
